# Generated by Django 4.2.5 on 2023-11-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_attos', '0004_fotos_last_updated_instagramprofile_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='atualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
