# Generated by Django 4.2.5 on 2023-11-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_attos', '0005_atualizacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='atualizacao',
        ),
    ]
