# Generated by Django 4.2.5 on 2023-11-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_attos', '0006_delete_atualizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotos',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='instagramprofile',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='quantidadedoadores',
            name='last_updated',
        ),
    ]
