# Generated by Django 4.2.5 on 2023-11-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_attos', '0009_fotos_last_updated_quantidadedoadores_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotos',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='instagramprofile',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='quantidadedoadores',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
