# Generated by Django 4.2.5 on 2023-11-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_attos', '0004_instagramprofile_last_updated'),
        ('app_attos', '0010_remove_fotos_last_updated_and_more'),
    ]

    operations = [
    ]
