# Generated by Django 4.2.5 on 2023-11-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_attos', '0011_merge_20231103_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramprofile',
            name='last_updated',
        ),
    ]
