# Generated by Django 4.2.5 on 2023-11-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_attos', '0015_userprofile_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='meta_anual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='valor_arrecadado',
            field=models.FloatField(default=0.0),
        ),
    ]
