# Generated by Django 4.2.5 on 2023-11-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_attos', '0016_userprofile_meta_anual_userprofile_valor_arrecadado'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ano_fundacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_ong',
            field=models.EmailField(default='defaul@default.com', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='endereco_ong',
            field=models.CharField(default='', max_length=100),
        ),
    ]
