name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: projetos-attos
  PYTHON_VERSION: '3.11'             

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r project_attos/requirements.txt

      - name: Install Selenium
        run: pip install selenium

      - name: Install Pillow
        run: |
          python -m pip install Pillow
          
      - name: Run  server
        run: python project_attos/manage.py runserver 


      - name: Run Tests
        run: python project_attos/manage.py test app_attos
    
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            .
            !venv/

      - name: Cleaning testing files
        run: |
          cd project_attos/
          rm db.sqlite3
          rm .env
          cd ..

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            project_attos
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'project-attos'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_86CB65BA00A34F2791F8A891220FEE4C }}
